# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5435/fingers_on_buzzers
spring.datasource.username=postgres
spring.datasource.password=dev1

# Frontend configuration
allowed-origins.frontend-host-url=http://localhost:5173

# Logging
logging.level.io.fingersonbuzzers.backend=DEBUG

# Monitoring
management.endpoints.enabled-by-default=true
